import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import styles from './page.module.scss';
const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 'auto', background: 'black' }} className={roboto.className}>
        {<div className={styles.container}>{children} </div>}
      </body>
    </html>
  );
}
